import {AbsoluteFill, interpolate, useCurrentFrame} from "remotion";
import {theme} from "../theme";
import {AdaptiveBilingualSubtitle} from "./compat";

type VideoBackdropProps = {
  title?: string;
};

export const VideoBackdrop = ({title = "AI WORKFLOW VIDEO"}: VideoBackdropProps) => {
  const frame = useCurrentFrame();
  const progress = interpolate(frame, [0, 450], [0, 1], {
    extrapolateLeft: "clamp",
    extrapolateRight: "clamp",
  });
  const caption =
    frame < 128
      ? {
          zh: "本期视频的口播剪辑以及上方的动画效果，全部是 AI 自动生成的，不知道你觉的效果如何。",
          en: "The voiceover edit and overlay animation are fully generated by AI.",
        }
      : frame < 318
        ? {
            zh: "在之前的视频中，尝试复刻了一个片段，效果差强人意，经过几天的调整，终于做出了一个完整的方案。",
            en: "After several days of iteration, the workflow became a complete solution.",
          }
        : {
            zh: "我已经把这一整套方案整理成了一个 skill 放在了评论区。",
            en: "I packaged the full workflow as a reusable skill in the comments.",
          };

  return (
    <AbsoluteFill
      style={{
        background: theme.colors.paper,
        fontFamily: theme.typography.body,
        color: theme.colors.ink,
        overflow: "hidden",
      }}
    >
      <div
        style={{
          position: "absolute",
          inset: 0,
          backgroundImage: `
            linear-gradient(rgba(20, 22, 26, 0.05) 1px, transparent 1px),
            linear-gradient(90deg, rgba(20, 22, 26, 0.05) 1px, transparent 1px)
          `,
          backgroundSize: "44px 44px",
          transform: `translate3d(${-progress * 36}px, ${-progress * 18}px, 0)`,
        }}
      />
      <div
        style={{
          position: "absolute",
          left: 110,
          top: 108,
          width: 1060,
          height: 610,
          borderRadius: 14,
          background: "#20242B",
          boxShadow: "0 34px 100px rgba(20, 22, 26, 0.24)",
          overflow: "hidden",
          border: "1px solid rgba(255,255,255,0.16)",
        }}
      >
        <div
          style={{
            height: 58,
            display: "flex",
            alignItems: "center",
            padding: "0 24px",
            gap: 10,
            color: "#EEF1F5",
            borderBottom: "1px solid rgba(255,255,255,0.12)",
          }}
        >
          <Dot color="#E45A4F" />
          <Dot color="#FFB000" />
          <Dot color="#18A999" />
          <div
            style={{
              marginLeft: 18,
              fontFamily: theme.typography.mono,
              fontSize: 17,
              color: "rgba(255,255,255,0.72)",
            }}
          >
            {title}
          </div>
        </div>
        <div
          style={{
            position: "absolute",
            left: 48,
            right: 48,
            top: 105,
            height: 310,
            borderRadius: 10,
            background:
              "linear-gradient(135deg, rgba(24,169,153,0.20), rgba(91,108,255,0.12)), #11151B",
            border: "1px solid rgba(255,255,255,0.12)",
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 42,
              top: 44,
              width: 260,
              height: 168,
              borderRadius: 8,
              background: "rgba(255,255,255,0.08)",
              border: "1px solid rgba(255,255,255,0.12)",
            }}
          />
          <div
            style={{
              position: "absolute",
              left: 340,
              right: 42,
              top: 46,
              display: "grid",
              gap: 18,
            }}
          >
            {[0, 1, 2, 3].map((item) => (
              <div
                key={item}
                style={{
                  height: 18,
                  width: `${88 - item * 11}%`,
                  borderRadius: 999,
                  background: "rgba(255,255,255,0.16)",
                }}
              />
            ))}
          </div>
        </div>
        <div
          style={{
            position: "absolute",
            left: 48,
            right: 48,
            bottom: 42,
            height: 98,
            borderRadius: 8,
            background: "rgba(255,255,255,0.07)",
            border: "1px solid rgba(255,255,255,0.1)",
            overflow: "hidden",
          }}
        >
          <div
            style={{
              position: "absolute",
              left: 0,
              top: 0,
              bottom: 0,
              width: `${18 + progress * 70}%`,
              background: "rgba(24,169,153,0.20)",
            }}
          />
          <div
            style={{
              position: "absolute",
              left: 24,
              right: 24,
              top: 34,
              display: "grid",
              gridTemplateColumns: "repeat(18, 1fr)",
              gap: 8,
            }}
          >
            {Array.from({length: 18}).map((_, index) => (
              <div
                key={index}
                style={{
                  height: 30 + ((index * 19) % 42),
                  alignSelf: "center",
                  borderRadius: 4,
                  background:
                    index / 18 < progress
                      ? theme.colors.teal
                      : "rgba(255,255,255,0.22)",
                }}
              />
            ))}
          </div>
        </div>
      </div>
      <AdaptiveBilingualSubtitle
        zh={caption.zh}
        en={caption.en}
        variant="bar"
        bottom={38}
        maxWidth={1680}
        reserveHeight={150}
      />
    </AbsoluteFill>
  );
};

const Dot = ({color}: {color: string}) => (
  <div style={{width: 12, height: 12, borderRadius: 999, background: color}} />
);
